### ISSUE TITLE
Expo v48 deprecated app.json entrypoint

### ISSUE THREAD

**Issue by jgoodhcg** [thheller/reagent-expo#13]
I don't understand how this works but from [the v48 deprecations](https://blog.expo.dev/expo-sdk-48-ccb8302e231)

> entryPoint has been removed from app.json / app.config.js. Use main in package.json instead.

I think this is breaking how shadow interfaces with metro and registering the root component with expo.

**Comment by thheller** [comment]
Sorry, I don't know what you mean either. What exactly is the problem?

There is not `entryPoint` [here](https://github.com/thheller/reagent-expo/blob/master/app.json), so the deprecation you mentioned doesn't seem relevant?

**Comment by jgoodhcg** [comment]
:sweat_smile:  My project was based on an older version before [this change](https://github.com/thheller/reagent-expo/commit/257f04c58ff60e98599e260e45f0d3f542e06356#diff-96677aa35debfefd031d9d34d9c70369754ee3acb2d9a9d4090e98612efee6f5).

I'll close this issue and try upgrading expo on a fresh fork of this repo.
