### ISSUE TITLE
Running tests with Expo

### ISSUE THREAD

**Issue by frankiesardo** [thheller/reagent-expo#5]
Hi @thheller thanks so much for providing this example, it is a pleasure to use shadow-cljs with expo.

I'm trying to run tests that use expo specific code but the usual way of running tests with shadow-cljs doesn't work.

Example:

```clj
{...
 :test
  {:target :node-test
   :output-to "out/node-tests.js"}
```

```clj
(ns test.app-test
  (:require
   [cljs.test :refer (deftest is)]
   ["expo" :as ex]
   ["react-native" :as rn]
   ["react" :as react]
   [reagent.core :as r]
   [shadow.expo :as expo]))

(deftest a-failing-test 
  (is (= 1 2)))
```

```
shadow-cljs compile test && node out/node-tests.js
```

Causes a variety of errors, probably because `expo` and `react-native` use non-standard javascript syntax and requires a first pass with webpack or metro (I'm not an expert as you can tell).

I'm used to write [snapshot UI tests](https://github.com/juxt/snap) with web react applications and I would like to accomplish the same in expo, help is appreciated 🚀

**Comment by thheller** [comment]
As the name implies `:node-test` is used to run `node` tests. It doesn't work with `react-native`.

I don't know anything about react-native/expo testing, Sorry.

**Comment by frankiesardo** [comment]
No problems, thanks anyway. I decided to open an issue in case anyone wants to add a `test` configuration for this sample project, but I can close it for now
